// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using TestOkApi.localhost;
//using Service;

namespace TestOkApi
{
  /// <summary>
  ///This is a test class for TestOkApi.localhost.Service and is intended
  ///to contain all TestOkApi.localhost.Service Unit Tests
  ///</summary>
  [TestClass()]
  public class ServiceTest
  {


    private TestContext testContextInstance;

    /// <summary>
    ///Gets or sets the test context which provides
    ///information about and functionality for the current test run.
    ///</summary>
    public TestContext TestContext
    {
      get
      {
        return testContextInstance;
      }
      set
      {
        testContextInstance = value;
      }
    }
    #region Additional test attributes
    // 
    //You can use the following additional attributes as you write your tests:
    //
    //Use ClassInitialize to run code before running the first test in the class
    //
    //[ClassInitialize()]
    //public static void MyClassInitialize(TestContext testContext)
    //{
    //}
    //
    //Use ClassCleanup to run code after all tests in a class have run
    //
    //[ClassCleanup()]
    //public static void MyClassCleanup()
    //{
    //}
    //
    //Use TestInitialize to run code before running each test
    //
    //[TestInitialize()]
    //public void MyTestInitialize()
    //{
    //}
    //
    //Use TestCleanup to run code after each test has run
    //
    //[TestCleanup()]
    //public void MyTestCleanup()
    //{
    //}
    //
    #endregion


    /// <summary>
    ///A test for AddImage (byte[])
    ///</summary>
    [TestMethod()]
    public void AddImageTest()
    {
      TestOkApi.localhost.Service target = new TestOkApi.localhost.Service(); // TODO: Use [AspNetDevelopmentServer] and TryUrlRedirection() to auto launch and bind web service.

      byte[] date = new byte[] {65, 66, 67, 68};

      //long expected = 0;
      long actual;

      actual = target.AddImage(date);

      //Assert.AreEqual(expected, actual, "TestOkApi.localhost.Service.AddImage did not return the expected value.");
      //Assert.Inconclusive("Verify the correctness of this test method.");
    }

  }


}
